<a href="https://colab.research.google.com/github/patelsaumya/numpy/blob/master/02_Creating%20NumPy%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Creating NumPy Arrays</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>What is NumPy Array?</h2>
</div>

NumPy arrays are datastructures to store multi-dimensional data. They are homogeneous and perform vectorized operations by default.

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Create NumPy array from a list</h2>
</div>

In [ ]:
import numpy as np

In [ ]:
L = [1, 2, 3, 4]
arr = np.array(L)
arr

array([1, 2, 3, 4])

__Check Type__

In [ ]:
type(arr)

numpy.ndarray

__Vectorized Multiplication works__

In [ ]:
# A list replicates
L * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
arr * 2

array([2, 4, 6, 8])

In [ ]:
# possible with list comprehension or For loop
[2*i for i in L]

[2, 4, 6, 8]

__Subset array__ (Slicing)

start: stop: step

[start, stop)

__Start and Stop Markers__

-1: Will put the marker at the end.

-length: Will put the marker at the beginning.

Note start and stop markers can be put past the index bounds, in which case the index-bound will be included.


__Stepper__

+ve step: step right (increasing order of index)

-ve step: step left (decreasing order of index)

In [ ]:
arr[1:3]

array([2, 3])

In [ ]:
arr[1:1]

array([], dtype=int64)

__Negative indexing is supported__

In [ ]:
arr[-3:-1]

array([2, 3])

In [ ]:
l = [1,2,3,4,5,6]

In [ ]:
l[0:10:1]

[1, 2, 3, 4, 5, 6]

In [ ]:
l[-1:-3:1]

[]

In [ ]:
l[10:-10:-1]

[6, 5, 4, 3, 2, 1]

In [ ]:
l[10:-6:-1]

[6, 5, 4, 3, 2]

__Reversing__

In [ ]:
arr[-1:1:-1]

array([4, 3])

__Arrays are homogenous__

Creating with list containing both numbers and characters will convert the numbers to characters. Because, Numpy arrays are homogenous.

In [ ]:
L = [1, 2, "A", "B"]
arr = np.array(L)
arr

array(['1', '2', 'A', 'B'], dtype='<U21')

Check data type

In [ ]:
arr.dtype

dtype('<U21')

Integer array

In [ ]:
L = [1, 2, 3, 4]
arr = np.array(L)
arr.dtype

dtype('int64')

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Two Dimensional Arrays</h2>
</div>

In [ ]:
L2 = [[1, 2, 3], 
      [4, 5, 6],
      [7, 8, 9]]

arr_L2 = np.array(L2)

In [ ]:
arr_L2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

__Array Indexing__

In [ ]:
arr_L2[0, :]

array([1, 2, 3])

In [ ]:
arr_L2[:, 1]

array([2, 5, 8])

__Convert back to list__

In [ ]:
arr_L2.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Change DataType</h2>
</div>

In [ ]:
# to string
arr_L2.astype('str')

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [ ]:
# to float
arr_L2.astype('float32')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Math Operations</h2>
</div>

In [ ]:
# Multiply
arr_L2 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
# Divide
quarter = arr_L2 / 4
quarter

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

In [ ]:
# Subtract
arr_L2 - quarter

array([[0.75, 1.5 , 2.25],
       [3.  , 3.75, 4.5 ],
       [5.25, 6.  , 6.75]])

In [ ]:
# Add
arr_L2 - quarter + arr_L2

array([[ 1.75,  3.5 ,  5.25],
       [ 7.  ,  8.75, 10.5 ],
       [12.25, 14.  , 15.75]])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Create Zeros and Ones Arrays</h2>
</div>

__Zeros__

In [ ]:
np.zeros_like(arr_L2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

__Ones__

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones_like(arr_L2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

__Diagonal__

In [ ]:
np.diag(arr_L2)

array([1, 5, 9])

__Identity Matrix__


In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])