<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Inspecting Arrays</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

__Let's first create one__

In [1]:
import numpy as np

In [2]:
L = [[1,2,3,4], 
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16],
     [17,18,19,20]]

arr = np.array(L)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

__Shape of the array__ - Number of items in each dimension (rows, columns)

In [3]:
arr.shape

(5, 4)

__ndim__ - Number of dimensions

In [4]:
arr.ndim

2

__Size__ - Total number of items

In [5]:
arr.size

20

__Datatype__

In [6]:
arr.dtype

dtype('int32')

Create in another dtype.

In [9]:
arr_int64 = np.array(L, dtype='int64')
arr_int64

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]], dtype=int64)

__Memory Occupied__ in bytes. 

In [10]:
# n_elements x bytes occupied by each
arr_int64.nbytes

160

8 Bytes per element. 8x8=64bits per element.

Total size needed including non-element attributes of array.

In [11]:
# Include non element attributes of array
from sys import getsizeof
getsizeof(arr_int64)

272

Check the bigger datatype array.

In [ ]:
arr_int64.nbytes

In [ ]:
getsizeof(arr_int64)

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Copy vs Reference</h2>
</div>

If you change the value of the reference array, the original also changes. Whereas, when changing the copy, the original remains unaffected.

In [12]:
arr_r = arr   # reference
arr_c = arr.copy()  # copy

In [13]:
arr_c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [14]:
arr_r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

Change value in `arr_c`

In [16]:
arr_c[0, 0] = 100
arr_c

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

`arr` remains unaffected.

In [17]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

Let's try the same on `arr_r`. Changes to `arr_r` will affect `arr`.

In [18]:
arr_r[0, 0] = 100
arr_r

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [19]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

__Check the id of objects__

`arr_r` is actually `arr`.

In [20]:
print(id(arr))
print(id(arr_c))
print(id(arr_r))

1567326826048
1567361179776
1567326826048


In [21]:
arr_r is arr

True

In [22]:
arr_c is arr

False