<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Extract Specific Items</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Import Data from csv file</h2>
</div>

In [1]:
import numpy as np
data = np.genfromtxt('Datasets/Mall_Customers_Int.csv', 
                     delimiter=",",
                     skip_header=1)

In [2]:
# CustomerID, Genre, Age, Annual_Income, Spending_Score
data

array([[  1.,   1.,  19.,  15.,  39.],
       [  2.,   1.,  21.,  15.,  81.],
       [  3.,   0.,  20.,  16.,   6.],
       [  4.,   0.,  23.,  16.,  77.],
       [  5.,   0.,  31.,  17.,  40.],
       [  6.,   0.,  22.,  17.,  76.],
       [  7.,   0.,  35.,  18.,   6.],
       [  8.,   0.,  23.,  18.,  nan],
       [  9.,   1.,  64.,  19.,   3.],
       [ 10.,   0.,  30.,  19.,  72.],
       [ 11.,   1.,  67.,  19.,  14.],
       [ 12.,   0.,  35.,  19.,  99.],
       [ 13.,   0.,  58.,  nan,  15.],
       [ 14.,   0.,  24.,  20.,  77.],
       [ 15.,   1.,  37.,  20.,  13.],
       [ 16.,   1.,  22.,  20.,  79.],
       [ 17.,   0.,  35.,  21.,  nan],
       [ 18.,   1.,  20.,  21.,  66.],
       [ 19.,   1.,  nan,  23.,  29.],
       [ 20.,   0.,  35.,  23.,  98.],
       [ 21.,   1.,  35.,  24.,  35.],
       [ 22.,   1.,  25.,  24.,  73.],
       [ 23.,   0.,  46.,  25.,   5.],
       [ 24.,   1.,  31.,  25.,  73.],
       [ 25.,   0.,  54.,  28.,  14.],
       [ 26.,   1.,  29.,

In [3]:
data.shape

(200, 5)

__Filter rows where the second column = 1.__

Create the mask and use that as the row / column argument.

In [4]:
mask = data[:, 1] == 1
mask[:10]  # first 10

array([ True,  True, False, False, False, False, False, False,  True,
       False])

In [5]:
data[mask, :]

array([[  1.,   1.,  19.,  15.,  39.],
       [  2.,   1.,  21.,  15.,  81.],
       [  9.,   1.,  64.,  19.,   3.],
       [ 11.,   1.,  67.,  19.,  14.],
       [ 15.,   1.,  37.,  20.,  13.],
       [ 16.,   1.,  22.,  20.,  79.],
       [ 18.,   1.,  20.,  21.,  66.],
       [ 19.,   1.,  nan,  23.,  29.],
       [ 21.,   1.,  35.,  24.,  35.],
       [ 22.,   1.,  25.,  24.,  73.],
       [ 24.,   1.,  31.,  25.,  73.],
       [ 26.,   1.,  29.,  28.,  82.],
       [ 28.,   1.,  35.,  28.,  61.],
       [ 31.,   1.,  60.,  30.,   4.],
       [ 33.,   1.,  53.,  33.,   4.],
       [ 34.,   1.,  18.,  33.,  92.],
       [ 42.,   1.,  24.,  38.,  92.],
       [ 43.,   1.,  48.,  39.,  36.],
       [ 52.,   1.,  33.,  42.,  60.],
       [ 54.,   1.,  59.,  43.,  60.],
       [ 56.,   1.,  47.,  43.,  41.],
       [ 58.,   1.,  69.,  44.,  46.],
       [ 60.,   1.,  53.,  46.,  46.],
       [ 61.,   1.,  70.,  46.,  56.],
       [ 62.,   1.,  19.,  46.,  55.],
       [ 65.,   1.,  63.,

__Rows that contain missing value in 4th column__

In [6]:
data[:, 3] == np.nan

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [7]:
data[np.isnan(data[:, 3]), :]

array([[13.,  0., 58., nan, 15.],
       [27.,  0., 45., nan, 32.],
       [57.,  0., 51., nan, 50.],
       [68.,  0., 68., nan, 48.]])

In [ ]:
# np.isnan(data[:, 3]) | np.isnan(data[:, 4]) | np.isnan(data[:, 5])

__Rows that contain missing in any of the columns__

The `any` method will return `True` if any of the values is true. Setting `axis=1` will do it row-wise. `axis=0` is column wise.

In [9]:
data[np.isnan(data).any(axis=1), :]

array([[ 8.,  0., 23., 18., nan],
       [13.,  0., 58., nan, 15.],
       [17.,  0., 35., 21., nan],
       [19.,  1., nan, 23., 29.],
       [27.,  0., 45., nan, 32.],
       [37.,  0., nan, 34., 17.],
       [57.,  0., 51., nan, 50.],
       [68.,  0., 68., nan, 48.]])

In [8]:
np.isnan(data).any(axis=1)

array([False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False,  True, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [10]:
~np.isnan(data).any(axis=1)

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

__Drop all rows that contain one or more missing__

In [11]:
data[~np.isnan(data).any(axis=1), :]

array([[  1.,   1.,  19.,  15.,  39.],
       [  2.,   1.,  21.,  15.,  81.],
       [  3.,   0.,  20.,  16.,   6.],
       [  4.,   0.,  23.,  16.,  77.],
       [  5.,   0.,  31.,  17.,  40.],
       [  6.,   0.,  22.,  17.,  76.],
       [  7.,   0.,  35.,  18.,   6.],
       [  9.,   1.,  64.,  19.,   3.],
       [ 10.,   0.,  30.,  19.,  72.],
       [ 11.,   1.,  67.,  19.,  14.],
       [ 12.,   0.,  35.,  19.,  99.],
       [ 14.,   0.,  24.,  20.,  77.],
       [ 15.,   1.,  37.,  20.,  13.],
       [ 16.,   1.,  22.,  20.,  79.],
       [ 18.,   1.,  20.,  21.,  66.],
       [ 20.,   0.,  35.,  23.,  98.],
       [ 21.,   1.,  35.,  24.,  35.],
       [ 22.,   1.,  25.,  24.,  73.],
       [ 23.,   0.,  46.,  25.,   5.],
       [ 24.,   1.,  31.,  25.,  73.],
       [ 25.,   0.,  54.,  28.,  14.],
       [ 26.,   1.,  29.,  28.,  82.],
       [ 28.,   1.,  35.,  28.,  61.],
       [ 29.,   0.,  40.,  29.,  31.],
       [ 30.,   0.,  23.,  29.,  87.],
       [ 31.,   1.,  60.,

__Get the maximum value in each row__

`axis=1` will do it row-wise.

In [14]:
data.max(axis=1)

array([ 39.,  81.,  20.,  77.,  40.,  76.,  35.,  nan,  64.,  72.,  67.,
        99.,  nan,  77.,  37.,  79.,  nan,  66.,  nan,  98.,  35.,  73.,
        46.,  73.,  54.,  82.,  nan,  61.,  40.,  87.,  60.,  73.,  53.,
        92.,  49.,  81.,  nan,  73.,  39.,  75.,  65.,  92.,  48.,  61.,
        49.,  65.,  55.,  48.,  49.,  50.,  52.,  60.,  54.,  60.,  55.,
        56.,  nan,  69.,  59.,  60.,  70.,  62.,  67.,  64.,  65.,  66.,
        67.,  nan,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

_If a row contains missing values, it returns `nan`. So use `np.nanmax` instead to ignore missing._

In [15]:
np.nanmax(data, axis=1)

array([ 39.,  81.,  20.,  77.,  40.,  76.,  35.,  23.,  64.,  72.,  67.,
        99.,  58.,  77.,  37.,  79.,  35.,  66.,  29.,  98.,  35.,  73.,
        46.,  73.,  54.,  82.,  45.,  61.,  40.,  87.,  60.,  73.,  53.,
        92.,  49.,  81.,  37.,  73.,  39.,  75.,  65.,  92.,  48.,  61.,
        49.,  65.,  55.,  48.,  49.,  50.,  52.,  60.,  54.,  60.,  55.,
        56.,  57.,  69.,  59.,  60.,  70.,  62.,  67.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

Equivalently, you have `nanmin`, `nanmean`, `nanmedian`, `nanpercentile` functions.

__Get the maximum value in each column__

In [ ]:
data.max(axis=0)

Ignore missing data with `nanmax`.

In [ ]:
np.nanmax(data, axis=0)

__Writing if-else logic using `np.where()`__

If-Else logic using `np.where()`.

Example logic: If the second column = 1, then, keep score (5th col) as is, else divide it by 2.

In [ ]:
np.where(data[:, 1] == 1, data[:, 4], data[:, 4]/2)

__Get the position of the maximum value in each row__

In [16]:
max_pos = np.argmax(data, axis=1)
max_pos

array([4, 4, 2, 4, 4, 4, 2, 4, 2, 4, 2, 4, 3, 4, 2, 4, 4, 4, 2, 4, 2, 4,
       2, 4, 2, 4, 3, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 0, 4, 2, 4, 2, 4,
       2, 4, 4, 0, 0, 0, 4, 4, 4, 4, 0, 0, 3, 2, 0, 0, 2, 0, 2, 0, 0, 0,
       0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

In [ ]:
data[:5]

In [17]:
# max values in each row.
[data[row, i] for row, i in enumerate(max_pos)]

[39.0,
 81.0,
 20.0,
 77.0,
 40.0,
 76.0,
 35.0,
 nan,
 64.0,
 72.0,
 67.0,
 99.0,
 nan,
 77.0,
 37.0,
 79.0,
 nan,
 66.0,
 nan,
 98.0,
 35.0,
 73.0,
 46.0,
 73.0,
 54.0,
 82.0,
 nan,
 61.0,
 40.0,
 87.0,
 60.0,
 73.0,
 53.0,
 92.0,
 49.0,
 81.0,
 nan,
 73.0,
 39.0,
 75.0,
 65.0,
 92.0,
 48.0,
 61.0,
 49.0,
 65.0,
 55.0,
 48.0,
 49.0,
 50.0,
 52.0,
 60.0,
 54.0,
 60.0,
 55.0,
 56.0,
 nan,
 69.0,
 59.0,
 60.0,
 70.0,
 62.0,
 67.0,
 64.0,
 65.0,
 66.0,
 67.0,
 nan,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 93.0,
 94.0,
 95.0,
 96.0,
 97.0,
 98.0,
 99.0,
 100.0,
 101.0,
 102.0,
 103.0,
 104.0,
 105.0,
 106.0,
 107.0,
 108.0,
 109.0,
 110.0,
 111.0,
 112.0,
 113.0,
 114.0,
 115.0,
 116.0,
 117.0,
 118.0,
 119.0,
 120.0,
 121.0,
 122.0,
 123.0,
 124.0,
 125.0,
 126.0,
 127.0,
 128.0,
 129.0,
 130.0,
 131.0,
 132.0,
 133.0,
 134.0,
 135.0,
 136.0,
 137.0,
 138.0,
 13

__Get the position of values that satisfy a given condition__

In [18]:
# Positions where a given condition is satisfied
pos = np.argwhere(data[:, 1] == 1)
pos[:5]

array([[ 0],
       [ 1],
       [ 8],
       [10],
       [14]], dtype=int64)

In [19]:
data[:5, :]

array([[ 1.,  1., 19., 15., 39.],
       [ 2.,  1., 21., 15., 81.],
       [ 3.,  0., 20., 16.,  6.],
       [ 4.,  0., 23., 16., 77.],
       [ 5.,  0., 31., 17., 40.]])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge</h2>
</div>

1. From `Mall_Customers_Int.csv`, find the row positions where 2nd column is 1 and 3rd column has value < 21. Extract the values from these columns. How many such rows exist?

2. Create a new array from `Mall_Customers_Int.csv` that has the value 1 if 2nd column = 1 and 3rd column < 21. Otherwise, it has the value 0.

```python
import numpy as np
data = np.genfromtxt('Datasets/Mall_Customers_Int.csv', 
                     delimiter=",",
                     skip_header=1)
```

Code URL: https://git.io/JZAWp

__Solutions__

In [ ]:
import numpy as np
data = np.genfromtxt('Datasets/Mall_Customers_Int.csv', 
                     delimiter=",",
                     skip_header=1)

In [ ]:
# Solution 1
pos = np.argwhere((data[:, 1] == 1) & (data[:, 2] < 21))
pos[:5]

In [ ]:
# how many such exist?
len(pos)

In [ ]:
# Solution 2
arr = np.where((data[:, 1] == 1) & (data[:, 2] < 21), 1, 0)
arr

In [ ]:
# Check
data[:5, :]