<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Statistical Summaries</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Define the datatype and import data</h2>
</div>

In [1]:
import numpy as np
dt = np.dtype([("Manufacturer", np.unicode_, 16),
               ("Model", np.unicode_, 16),
               ("Type", np.unicode_, 16),
               ("Min.Price", np.float64),
               ("Price", np.float64),
               ("Max.Price", np.float64),
               ("MPG.city", np.float64),
               ("MPG.highway", np.float64),
               ("AirBags", np.unicode_, 16),
               ("DriveTrain", np.unicode_, 16),
               ("Cylinders", np.unicode_, 16),
               ("EngineSize", np.float64),
               ("Horsepower", np.float64),
               ("RPM", np.float64),
               ("Rev.per.mile", np.float64),
               ("Man.trans.avail", np.unicode_, 16),
               ("Fuel.tank.capacity", np.float64),
               ("Passengers", np.float64),
               ("Length", np.float64),
               ("Wheelbase", np.float64),
               ("Width", np.float64),
               ("Turn.circle", np.float64),
               ("Rear.seat.room", np.float64),
               ("Luggage.room", np.float64),
               ("Weight", np.float64),
               ("Origin", np.unicode_, 16),
               ("Make", np.unicode_, 16)])

dt

dtype([('Manufacturer', '<U16'), ('Model', '<U16'), ('Type', '<U16'), ('Min.Price', '<f8'), ('Price', '<f8'), ('Max.Price', '<f8'), ('MPG.city', '<f8'), ('MPG.highway', '<f8'), ('AirBags', '<U16'), ('DriveTrain', '<U16'), ('Cylinders', '<U16'), ('EngineSize', '<f8'), ('Horsepower', '<f8'), ('RPM', '<f8'), ('Rev.per.mile', '<f8'), ('Man.trans.avail', '<U16'), ('Fuel.tank.capacity', '<f8'), ('Passengers', '<f8'), ('Length', '<f8'), ('Wheelbase', '<f8'), ('Width', '<f8'), ('Turn.circle', '<f8'), ('Rear.seat.room', '<f8'), ('Luggage.room', '<f8'), ('Weight', '<f8'), ('Origin', '<U16'), ('Make', '<U16')])

In [2]:
import numpy as np
data = np.genfromtxt('Datasets/cars93.csv', 
                     delimiter=",", 
                     dtype=dt,
                     skip_header=1)

data

array([('"Acura"', '"Integra"', '"Small"', 12.9, 15.9, 18.8, 25., 31., '"None"', '"Front"', '"4"', 1.8, 140., 6300., 2890., '"Yes"', 13.2, 5., 177., 102., 68., 37., 26.5, 11., 2705., '"non-USA"', '"Acura Integra"'),
       ('"Acura"', '"Legend"', '"Midsize"', 29.2, 33.9, 38.7, 18., 25., '"Driver & Passen', '"Front"', '"6"', 3.2, 200., 5500., 2335., '"Yes"', 18. , 5., 195., 115., 71., 38., 30. , 15., 3560., '"non-USA"', '"Acura Legend"'),
       ('"Audi"', '"90"', '"Compact"', 25.9, 29.1, 32.3, 20., 26., '"Driver only"', '"Front"', '"6"', 2.8, 172., 5500., 2280., '"Yes"', 16.9, 5., 180., 102., 67., 37., 28. , 14., 3375., '"non-USA"', '"Audi 90"'),
       ('"Audi"', '"100"', '"Midsize"', 30.8, 37.7, 44.6, 19., 26., '"Driver & Passen', '"Front"', '"6"', 2.8, 172., 5500., 2535., '"Yes"', 21.1, 6., 193., 106., 70., 37., 31. , 17., 3405., '"non-USA"', '"Audi 100"'),
       ('"BMW"', '"535i"', '"Midsize"', 23.7, 30. , 36.2, 22., 30., '"Driver only"', '"Rear"', '"4"', 3.5, 208., 5700., 2545., 

__Numeric Variable: MPG.highway__

In [3]:
data.shape

(93,)

In [4]:
data["Weight"]

array([2705., 3560., 3375., 3405., 3640., 2880., 3470., 4105., 3495.,
       3620., 3935., 2490., 2785., 3240., 3195., 3715., 4025., 3910.,
       3380., 3515., 3085., 3570., 2270., 2670., 2970., 3705., 3080.,
       3805., 2295., 3490., 1845., 2530., 2690., 2850., 2710., 3735.,
       3325., 3950., 1695., 2475., 2865., 2350., 3040., 2345., 2620.,
       2285., 2885., 4000., 3510., 3515., 3695., 4055., 2325., 2440.,
       2970., 3735., 2895., 2920., 3525., 2450., 3610., 2295., 3730.,
       2545., 3050., 4100., 3200., 2910., 2890., 3715., 3470., 2640.,
       2350., 2575., 3240., 3450., 3495., 2775., 2495., 2045., 2490.,
       3085., 1965., 2055., 2950., 3030., 3785., 2240., 3960., 2985.,
       2810., 2985., 3245.])

__Min and Max__

In [5]:
# Max and min
data["Weight"].max(), data["Weight"].min()

(4105.0, 1695.0)

__Mean and Median__

In [6]:
# Mean and Median
np.mean(data["Weight"]), np.median(data["Weight"])

(3072.9032258064517, 3040.0)

__Percentile__

In [7]:
# Percentile
np.percentile(data["Weight"], 50)

3040.0

In [8]:
# Quantile
np.quantile(data["Weight"], q=.25)

2620.0

__Standard Deviation and Variance__

In [9]:
# Standard and #variance
np.std(data['Weight']), np.var(data['Weight'])

(586.7164519048623, 344236.19493583066)

__Coefficient of Variation__

Coefficient of variatio = Standard deviation / Mean. Used to understand the extend of deviation irrespective of scale of the variable.

In [10]:
# Standard and #variance
np.std(data['Weight'])/np.mean(data['Weight'])

0.190932290668179

__Covariance and Correlation__

In [ ]:
data[['MPGcity', 'Weight']]

In [11]:
# Correlation
np.corrcoef(data['Weight'], data["MPGcity"])

array([[ 1.        , -0.84313855],
       [-0.84313855,  1.        ]])

In [12]:
# Covariance matrix
np.cov(data['Weight'], data["MPGcity"])

array([[ 3.47977893e+05, -2.79509467e+03],
       [-2.79509467e+03,  3.15822814e+01]])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge 1</h2>
</div>

With following data (introduce artificial missing values)
  - Fill the missing values with the mean
  - Fill the missing values with the average of the prior and next values.

__Input__
```python
import numpy as np
arr = np. array([112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118, 115,
               126, 141, 135, 125, 149, 170, 170, 158, 133, 114, 140, 145, 150,
               178, 163, 172, 178, 199, 199, 184, 162, 146, 166, 171, 180, 193,
               181, 183, 218, 230, 242, 209, 191, 172, 194, 196, 196, 236, 235,
               229, 243, 264, 272, 237, 211, 180, 201, 204, 188, 235, 227, 234,
               264, 302, 293, 259, 229, 203, 229, 242, 233, 267, 269, 270, 315,
               364, 347, 312, 274, 237, 278, 284, 277, 317, 313, 318, 374, 413,
               405, 355, 306, 271, 306, 315, 301, 356, 348, 355, 422, 465, 467,
               404, 347, 305, 336, 340, 318, 362, 348, 363, 435, 491, 505, 404,
               359, 310, 337, 360, 342, 406, 396, 420, 472, 548, 559, 463, 407,
               362, 405, 417, 391, 419, 461, 472, 535, 622, 606, 508, 461, 390,
               432], dtype=np.float)
arr

arr_miss = arr.copy()

# Introduce missing values
np.random.seed(100)
missing_loc = []
for i in range(5):
    loc = np.random.randint(0, len(arr_miss)); missing_loc.append(loc)
    arr_miss[loc] = np.nan
    
arr_miss
```

__Code URL:__ https://git.io/JnGng

__Solution__

In [19]:
import numpy as np
arr = np. array([112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118, 115,
               126, 141, 135, 125, 149, 170, 170, 158, 133, 114, 140, 145, 150,
               178, 163, 172, 178, 199, 199, 184, 162, 146, 166, 171, 180, 193,
               181, 183, 218, 230, 242, 209, 191, 172, 194, 196, 196, 236, 235,
               229, 243, 264, 272, 237, 211, 180, 201, 204, 188, 235, 227, 234,
               264, 302, 293, 259, 229, 203, 229, 242, 233, 267, 269, 270, 315,
               364, 347, 312, 274, 237, 278, 284, 277, 317, 313, 318, 374, 413,
               405, 355, 306, 271, 306, 315, 301, 356, 348, 355, 422, 465, 467,
               404, 347, 305, 336, 340, 318, 362, 348, 363, 435, 491, 505, 404,
               359, 310, 337, 360, 342, 406, 396, 420, 472, 548, 559, 463, 407,
               362, 405, 417, 391, 419, 461, 472, 535, 622, 606, 508, 461, 390,
               432], dtype=np.float)
arr

arr_miss = arr.copy()
arr_miss

array([112., 118., 132., 129., 121., 135., 148., 148., 136., 119., 104.,
       118., 115., 126., 141., 135., 125., 149., 170., 170., 158., 133.,
       114., 140., 145., 150., 178., 163., 172., 178., 199., 199., 184.,
       162., 146., 166., 171., 180., 193., 181., 183., 218., 230., 242.,
       209., 191., 172., 194., 196., 196., 236., 235., 229., 243., 264.,
       272., 237., 211., 180., 201., 204., 188., 235., 227., 234., 264.,
       302., 293., 259., 229., 203., 229., 242., 233., 267., 269., 270.,
       315., 364., 347., 312., 274., 237., 278., 284., 277., 317., 313.,
       318., 374., 413., 405., 355., 306., 271., 306., 315., 301., 356.,
       348., 355., 422., 465., 467., 404., 347., 305., 336., 340., 318.,
       362., 348., 363., 435., 491., 505., 404., 359., 310., 337., 360.,
       342., 406., 396., 420., 472., 548., 559., 463., 407., 362., 405.,
       417., 391., 419., 461., 472., 535., 622., 606., 508., 461., 390.,
       432.])

In [20]:
# Introduce missing values
np.random.seed(100)
missing_loc = []
for i in range(5):
    loc = np.random.randint(0, len(arr_miss)); missing_loc.append(loc)
    arr_miss[loc] = np.nan
    
arr_miss

array([112., 118., 132., 129., 121., 135., 148., 148.,  nan, 119., 104.,
       118., 115., 126., 141., 135., 125., 149., 170., 170., 158., 133.,
       114., 140.,  nan, 150., 178., 163., 172., 178., 199., 199., 184.,
       162., 146., 166., 171., 180., 193., 181., 183., 218., 230., 242.,
       209., 191., 172., 194., 196., 196., 236., 235., 229., 243., 264.,
       272., 237., 211., 180., 201., 204., 188., 235., 227., 234., 264.,
       302.,  nan, 259., 229., 203., 229., 242., 233., 267., 269., 270.,
       315., 364., 347., 312., 274., 237., 278., 284., 277., 317.,  nan,
       318., 374., 413., 405., 355., 306., 271., 306., 315., 301., 356.,
       348., 355., 422., 465.,  nan, 404., 347., 305., 336., 340., 318.,
       362., 348., 363., 435., 491., 505., 404., 359., 310., 337., 360.,
       342., 406., 396., 420., 472., 548., 559., 463., 407., 362., 405.,
       417., 391., 419., 461., 472., 535., 622., 606., 508., 461., 390.,
       432.])

In [15]:
# 1. Fill missing with mean
arr_miss[np.isnan(arr_miss)] = np.nanmean(arr_miss).round(2)
arr_miss

array([112.  , 118.  , 132.  , 129.  , 121.  , 135.  , 148.  , 148.  ,
       280.64, 119.  , 104.  , 118.  , 115.  , 126.  , 141.  , 135.  ,
       125.  , 149.  , 170.  , 170.  , 158.  , 133.  , 114.  , 140.  ,
       280.64, 150.  , 178.  , 163.  , 172.  , 178.  , 199.  , 199.  ,
       184.  , 162.  , 146.  , 166.  , 171.  , 180.  , 193.  , 181.  ,
       183.  , 218.  , 230.  , 242.  , 209.  , 191.  , 172.  , 194.  ,
       196.  , 196.  , 236.  , 235.  , 229.  , 243.  , 264.  , 272.  ,
       237.  , 211.  , 180.  , 201.  , 204.  , 188.  , 235.  , 227.  ,
       234.  , 264.  , 302.  , 280.64, 259.  , 229.  , 203.  , 229.  ,
       242.  , 233.  , 267.  , 269.  , 270.  , 315.  , 364.  , 347.  ,
       312.  , 274.  , 237.  , 278.  , 284.  , 277.  , 317.  , 280.64,
       318.  , 374.  , 413.  , 405.  , 355.  , 306.  , 271.  , 306.  ,
       315.  , 301.  , 356.  , 348.  , 355.  , 422.  , 465.  , 280.64,
       404.  , 347.  , 305.  , 336.  , 340.  , 318.  , 362.  , 348.  ,
      

In [16]:
print(arr_miss[missing_loc])
print(arr[missing_loc])

[280.64 280.64 280.64 280.64 280.64]
[136. 145. 293. 467. 313.]


__Re-run `arr_miss` creation again.__

In [21]:
# 2. Fill missing with the mean of adjacent values
for i, val in enumerate(arr_miss):
    if np.isnan(val):
        arr_miss[i] = np.nanmean([arr_miss[i-1], arr_miss[i+1]]).round(2)

In [22]:
print(arr_miss[missing_loc])
print(arr[missing_loc])

[133.5 145.  280.5 434.5 317.5]
[136. 145. 293. 467. 313.]


<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge 2</h2>
</div>

For the following array:
  1. Find the interquartile range
  2. Cap the values at 5%ile and 95%ile. Replace values greater than 95%ile with 95%ile value.


```python
import numpy as np

# turn off scientific (e+02)  notations.
np.set_printoptions(suppress=True)  

# Create normal
np.random.seed(100)
arr = np.random.normal(100, 75, size=300).round(3)
arr
```

__Code URL:__ https://git.io/JnGBb  

__Solution__

In [ ]:
import numpy as np

# turn off scientific (e+02)  notations.
np.set_printoptions(suppress=True)  

# Create normal
np.random.seed(100)
arr = np.random.normal(100, 75, size=300).round(3)
arr

__Solution__

In [23]:
# 1. InterQuartile Range
q25 = np.quantile(arr, 0.25)
q75 = np.quantile(arr, 0.75)
iqr = q75 - q25
print("IQR: ", iqr)

IQR:  180.5


In [24]:
# 2. Capping

# Comput the percentiles
q5 = np.quantile(arr, 0.05)
q95 = np.quantile(arr, 0.95)
print(q5)
print(q95)

121.6
488.14999999999986


In [25]:
# Cap it
arr = np.where(arr < q5, q5, arr)
arr = np.where(arr > q95, q95, arr)

arr[:100]

array([121.6, 121.6, 132. , 129. , 121.6, 135. , 148. , 148. , 136. ,
       121.6, 121.6, 121.6, 121.6, 126. , 141. , 135. , 125. , 149. ,
       170. , 170. , 158. , 133. , 121.6, 140. , 145. , 150. , 178. ,
       163. , 172. , 178. , 199. , 199. , 184. , 162. , 146. , 166. ,
       171. , 180. , 193. , 181. , 183. , 218. , 230. , 242. , 209. ,
       191. , 172. , 194. , 196. , 196. , 236. , 235. , 229. , 243. ,
       264. , 272. , 237. , 211. , 180. , 201. , 204. , 188. , 235. ,
       227. , 234. , 264. , 302. , 293. , 259. , 229. , 203. , 229. ,
       242. , 233. , 267. , 269. , 270. , 315. , 364. , 347. , 312. ,
       274. , 237. , 278. , 284. , 277. , 317. , 313. , 318. , 374. ,
       413. , 405. , 355. , 306. , 271. , 306. , 315. , 301. , 356. ,
       348. ])

In [26]:
arr.max(), arr.min()

(488.14999999999986, 121.6)