<a href="https://colab.research.google.com/github/patelsaumya/numpy/blob/master/11_Reshaping%20and%20Manipulating%20Axis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Reshaping and New Axis</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

In [ ]:
import numpy as np

__Create 3x2 array__

In [ ]:
arr = np.array([[1,2],[3,4],[5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr.shape

(3, 2)

__Reshape it to 2 rows and 3 cols.__

In [ ]:
arr2 = arr.reshape(2,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(id(arr))
print(id(arr2))

1880374814960
1880375891728


__If you don't know the number of rows but know the columns before hand, set n_rows=-1__

In [ ]:
arr = np.arange(63)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62])

In [ ]:
arr.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62]])

__`resize()` changes the shape of the array in place. No need to reassign.__

In [ ]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
print(id(arr))

1880375933088


In [ ]:
arr.resize(4, 3)

In [ ]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
print(id(arr))

1880375933088


__Add an axis: Column or Row__

In [ ]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
# make it as a column of a 2d array
arr1 = arr[:, np.newaxis]
arr1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
arr1.shape

(6, 1)

In [ ]:
# make it as a row of a 2d array
arr2 = arr[np.newaxis, :]
arr2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
arr2.shape

(1, 6)

__Flatten an array__

Flattens an array by creating a new copy of it.

In [ ]:
arr = np.array([[1,2],[3,4],[5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a2 = arr.flatten()
a2

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(id(arr))
print(id(a2))

1880375975648
1880376002560


__Ravel__

Ravel does not create a new array. It is a flattened view of the original array.

In [ ]:
a3 = arr.ravel()

In [ ]:
id(arr)

1880375975648

In [ ]:
# same id as arr. So same as `arr`
print(id(a3))

1880376004160


In [ ]:
a3

In [ ]:
arr

To iterate, use `arr.flat()`.

In [ ]:
for element in arr.flat:
    print(element)

1
2
3
4
5
6


<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge</h2>
</div>

Reshape the following array to a 2D array containing 4 rows. Try doing it without calculating the number of columns required.

__Input__
```python
a = np.arange(24)
```

__Solution__

In [ ]:
# 1.
a = np.arange(24)
a.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
# 2. Better solution
a = np.arange(24)
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])