<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Sequences and Repetitions</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

__Create a simple sequence__

In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

__Sequence with steps__

In [2]:
# steps of 3
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

Reverse direction with negatve step.

In [3]:
np.arange(20, 1, -3)

array([20, 17, 14, 11,  8,  5,  2])

__When you don't know the step size__

Use `np.linspace` Linear and equally spaced sequence.

In [4]:
np.linspace(1, 2, 10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

To see the stepsize used, set `retstep=True`.

In [5]:
np.linspace(1, 2, 10, retstep=True)

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 0.1111111111111111)

__Log Space__

Similar to `linspace` but in log.

In [6]:
# log values: log(10) = 1 to log(100) = 2
np.logspace(1, 2, 10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

__Repeating Sequences__

`np.tile(x, n)` will repeat sequence `x`, `n` times.

In [7]:
np.tile([1,2,3,4], 3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

Repeat each item n times.

In [8]:
np.repeat([1,2,3,4], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge</h2>
</div>

Create the following pattern using the following input, without hardcoding (typing sequence by hand). There can be multiple approaches.

__Input__

```python
a = np.array([1,2,3])
```

__Output__

```python
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

__Solution__

In [12]:
a = np.array([1,2,3])
np.array([np.repeat(a, 3), np.tile(a, 3)]).flatten()

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])