<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Concatenate and Split</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

__Create two 2D arrays__

In [1]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
b = a * 2
b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Concatenate Horizontally</h2>
</div>

(i) `hstack`

Takes one argument only

In [3]:
np.hstack([a, b])

array([[ 0,  1,  2,  3,  0,  2,  4,  6],
       [ 4,  5,  6,  7,  8, 10, 12, 14],
       [ 8,  9, 10, 11, 16, 18, 20, 22]])

(ii) `c_`

In [4]:
np.c_[a, b]

array([[ 0,  1,  2,  3,  0,  2,  4,  6],
       [ 4,  5,  6,  7,  8, 10, 12, 14],
       [ 8,  9, 10, 11, 16, 18, 20, 22]])

(iii)  `column_stack`

Takes one argument only

In [5]:
np.column_stack([a, b])

array([[ 0,  1,  2,  3,  0,  2,  4,  6],
       [ 4,  5,  6,  7,  8, 10, 12, 14],
       [ 8,  9, 10, 11, 16, 18, 20, 22]])

In [6]:
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  0,  2,  4,  6],
       [ 4,  5,  6,  7,  8, 10, 12, 14],
       [ 8,  9, 10, 11, 16, 18, 20, 22]])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Concatenate Vertically</h2>
</div>

In [7]:
np.vstack([a, b])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [8]:
np.r_[a, b]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [9]:
np.row_stack([a, b])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [10]:
np.concatenate([a, b], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

__Splitting an array__

In [11]:
arr = np.concatenate([a, b, a, b])
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

Cut horizontally into 2 equal pieces

In [12]:
# Split vertically in 2 pieces (horizontal cut)
np.vsplit(arr, 2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]]), array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]])]

Cut horizontally into 3 pieces at 3 and 7 positions.

In [13]:
np.vsplit(arr, [3, 7])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 0,  1,  2,  3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]])]

In [14]:
# Split horizontally in 2 pieces (vertical cut)
np.hsplit(arr, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [ 0,  2],
        [ 8, 10],
        [16, 18],
        [ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [ 0,  2],
        [ 8, 10],
        [16, 18]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [ 4,  6],
        [12, 14],
        [20, 22],
        [ 2,  3],
        [ 6,  7],
        [10, 11],
        [ 4,  6],
        [12, 14],
        [20, 22]])]

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge</h2>
</div>

Split the following dataset into smaller datasets containing 5 rows each. Save each row as a .npz file on disk, named starting from 1.npz, 2.npz and so on.

__Input Code__
```python
import numpy as np
arr = np.genfromtxt("Datasets/data.txt")
```

__Solution__

In [15]:
import numpy as np
arr = np.genfromtxt("Datasets/data.txt")
arr

array([[ 1.     , 87.     , 57.54435],
       [ 2.     ,  8.     ,  7.31704],
       [ 3.     , 56.     , 56.82095],
       [ 4.     , 63.     , 64.15579],
       [ 5.     ,  2.     ,  5.74522],
       [ 6.     , 45.     , 19.56758],
       [ 7.     , 43.     , 39.62271],
       [ 8.     , 47.     , 34.95107],
       [ 9.     ,  2.     ,  9.38692],
       [10.     , 79.     , 36.41022],
       [11.     , 67.     , 49.83894],
       [12.     , 24.     , 23.47974],
       [13.     , 61.     , 72.55357],
       [14.     , 85.     , 39.24693],
       [15.     , 63.     , 53.6279 ],
       [16.     ,  2.     , 16.72441],
       [17.     , 29.     , 37.25533],
       [18.     , 45.     , 18.78498],
       [19.     , 33.     , 19.8089 ],
       [20.     , 28.     , 46.03384],
       [21.     , 21.     , 23.7864 ],
       [22.     , 27.     , 44.42627],
       [23.     , 65.     , 34.94804],
       [24.     , 61.     , 53.49576],
       [25.     , 10.     , 25.98564]])

In [16]:
# Solution
L = np.vsplit(arr, 5)

In [17]:
L

[array([[ 1.     , 87.     , 57.54435],
        [ 2.     ,  8.     ,  7.31704],
        [ 3.     , 56.     , 56.82095],
        [ 4.     , 63.     , 64.15579],
        [ 5.     ,  2.     ,  5.74522]]),
 array([[ 6.     , 45.     , 19.56758],
        [ 7.     , 43.     , 39.62271],
        [ 8.     , 47.     , 34.95107],
        [ 9.     ,  2.     ,  9.38692],
        [10.     , 79.     , 36.41022]]),
 array([[11.     , 67.     , 49.83894],
        [12.     , 24.     , 23.47974],
        [13.     , 61.     , 72.55357],
        [14.     , 85.     , 39.24693],
        [15.     , 63.     , 53.6279 ]]),
 array([[16.     ,  2.     , 16.72441],
        [17.     , 29.     , 37.25533],
        [18.     , 45.     , 18.78498],
        [19.     , 33.     , 19.8089 ],
        [20.     , 28.     , 46.03384]]),
 array([[21.     , 21.     , 23.7864 ],
        [22.     , 27.     , 44.42627],
        [23.     , 65.     , 34.94804],
        [24.     , 61.     , 53.49576],
        [25.     , 10.     , 25.

In [18]:
for i, arr in enumerate(L):
    np.savez(f"TEMP/{i}.npz", arr)