<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Sorting Methods</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

1. Regular Sorting
2. argsort
3. lexsort

In [1]:
import numpy as np
np.set_printoptions(suppress=True)  

In [2]:
data = np.genfromtxt("Datasets/Lifecyclesavings.csv", delimiter=",", skip_header=1)
data[:10]

array([[  11.43,   29.35,    2.87, 2329.68,    2.87],
       [  12.07,   23.32,    4.41, 1507.99,    3.93],
       [  13.17,   23.8 ,    4.43, 2108.47,    3.82],
       [   5.75,   41.89,    1.67,  189.13,    0.22],
       [  12.88,   42.19,    0.83,  728.47,    4.56],
       [   8.79,   31.72,    2.85, 2982.88,    2.43],
       [   0.6 ,   39.74,    1.34,  662.86,    2.67],
       [  11.9 ,   44.75,    0.67,  289.52,    6.51],
       [   4.98,   46.64,    1.06,  276.65,    3.08],
       [  10.78,   47.64,    1.14,  471.24,    2.8 ]])

In [3]:
# Define Column names and Datatype 
dt = {'names':["sr","pop15","pop75","dpi","ddpi"], 
      'formats':[np.float, np.float, np.float, np.float, np.float]}
data.dtype=dt

In [4]:
data.shape

(50, 1)

In [5]:
data[:10]

array([[(11.43, 29.35, 2.87, 2329.68, 2.87)],
       [(12.07, 23.32, 4.41, 1507.99, 3.93)],
       [(13.17, 23.8 , 4.43, 2108.47, 3.82)],
       [( 5.75, 41.89, 1.67,  189.13, 0.22)],
       [(12.88, 42.19, 0.83,  728.47, 4.56)],
       [( 8.79, 31.72, 2.85, 2982.88, 2.43)],
       [( 0.6 , 39.74, 1.34,  662.86, 2.67)],
       [(11.9 , 44.75, 0.67,  289.52, 6.51)],
       [( 4.98, 46.64, 1.06,  276.65, 3.08)],
       [(10.78, 47.64, 1.14,  471.24, 2.8 )]],
      dtype=[('sr', '<f8'), ('pop15', '<f8'), ('pop75', '<f8'), ('dpi', '<f8'), ('ddpi', '<f8')])

`data.sort()` will sort the values inplace.

In [6]:
# Sort Row wise
data.sort(axis=0)
data[:10]

array([[(0.6 , 39.74, 1.34,  662.86, 2.67)],
       [(1.27, 34.03, 3.08, 1900.1 , 1.12)],
       [(2.02, 41.18, 1.05,  220.56, 1.03)],
       [(2.81, 46.12, 1.21,  249.87, 1.13)],
       [(3.01, 46.05, 0.87,  289.71, 1.48)],
       [(3.59, 46.31, 1.19,  287.77, 2.19)],
       [(3.98, 41.74, 0.91,  207.68, 5.81)],
       [(4.44, 43.56, 1.2 ,  568.56, 3.61)],
       [(4.71, 47.2 , 0.66,  242.69, 5.08)],
       [(4.98, 46.64, 1.06,  276.65, 3.08)]],
      dtype=[('sr', '<f8'), ('pop15', '<f8'), ('pop75', '<f8'), ('dpi', '<f8'), ('ddpi', '<f8')])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Descending Sort</h2>
</div>

In [7]:
# Descending sort
data.sort(axis=0)
data[::-1][:10]

array([[(21.1 , 27.01, 1.91, 1257.28, 8.21)],
       [(18.56, 45.25, 0.56,  138.33, 5.14)],
       [(16.85, 24.42, 3.93, 2496.53, 3.99)],
       [(15.48, 32.54, 2.47,  601.05, 8.12)],
       [(14.65, 24.71, 3.25, 1740.7 , 7.66)],
       [(14.28, 24.52, 3.48, 1390.  , 3.54)],
       [(14.13, 23.49, 3.73, 2630.96, 2.7 )],
       [(13.3 , 31.92, 1.52,  250.96, 2.  )],
       [(13.17, 23.8 , 4.43, 2108.47, 3.82)],
       [(12.88, 42.19, 0.83,  728.47, 4.56)]],
      dtype=[('sr', '<f8'), ('pop15', '<f8'), ('pop75', '<f8'), ('dpi', '<f8'), ('ddpi', '<f8')])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Let's work with data in the 2D format, without the dtype</h2>
</div>

In [8]:
data = np.genfromtxt("Datasets/Lifecyclesavings.csv", delimiter=",", skip_header=1)
data[:10]

array([[  11.43,   29.35,    2.87, 2329.68,    2.87],
       [  12.07,   23.32,    4.41, 1507.99,    3.93],
       [  13.17,   23.8 ,    4.43, 2108.47,    3.82],
       [   5.75,   41.89,    1.67,  189.13,    0.22],
       [  12.88,   42.19,    0.83,  728.47,    4.56],
       [   8.79,   31.72,    2.85, 2982.88,    2.43],
       [   0.6 ,   39.74,    1.34,  662.86,    2.67],
       [  11.9 ,   44.75,    0.67,  289.52,    6.51],
       [   4.98,   46.64,    1.06,  276.65,    3.08],
       [  10.78,   47.64,    1.14,  471.24,    2.8 ]])

In [9]:
data.shape

(50, 5)

Trying to sort a 2D array will sort every column of that array. As a result, the row contents get disturbed. Careful!

In [10]:
data.sort(axis=0)
data[:10]

array([[  0.6 ,  21.44,   0.56,  88.94,   0.22],
       [  1.27,  21.8 ,   0.58, 123.58,   0.53],
       [  2.02,  23.27,   0.66, 138.33,   0.67],
       [  2.81,  23.31,   0.67, 152.01,   1.03],
       [  3.01,  23.32,   0.83, 189.13,   1.12],
       [  3.59,  23.49,   0.87, 207.68,   1.13],
       [  3.98,  23.8 ,   0.9 , 220.56,   1.48],
       [  4.44,  24.42,   0.91, 232.44,   1.54],
       [  4.71,  24.52,   0.96, 242.69,   1.57],
       [  4.98,  24.71,   1.05, 249.87,   1.76]])

Re-import original data and use argsort instead.

In [11]:
data = np.genfromtxt("Datasets/Lifecyclesavings.csv", delimiter=",", skip_header=1)
data[:10]

array([[  11.43,   29.35,    2.87, 2329.68,    2.87],
       [  12.07,   23.32,    4.41, 1507.99,    3.93],
       [  13.17,   23.8 ,    4.43, 2108.47,    3.82],
       [   5.75,   41.89,    1.67,  189.13,    0.22],
       [  12.88,   42.19,    0.83,  728.47,    4.56],
       [   8.79,   31.72,    2.85, 2982.88,    2.43],
       [   0.6 ,   39.74,    1.34,  662.86,    2.67],
       [  11.9 ,   44.75,    0.67,  289.52,    6.51],
       [   4.98,   46.64,    1.06,  276.65,    3.08],
       [  10.78,   47.64,    1.14,  471.24,    2.8 ]])

`np.argsort` gives the row positions of the numbers in increasing order.

In [12]:
# get row positions of increasing values.
x = np.argsort(data[:, 0])
x

array([ 6, 18, 31, 41, 16, 11, 23, 30, 49,  8, 40,  3, 38, 29, 43, 17, 46,
       42,  5, 48, 19, 44, 47, 26, 24, 28, 15,  9, 35, 12, 20,  0, 37,  7,
        1, 34, 14, 13, 32, 33,  4,  2, 36, 39, 21, 27, 25, 10, 45, 22],
      dtype=int64)

In [13]:
# sort the data
data[x, :][:10]

array([[   0.6 ,   39.74,    1.34,  662.86,    2.67],
       [   1.27,   34.03,    3.08, 1900.1 ,    1.12],
       [   2.02,   41.18,    1.05,  220.56,    1.03],
       [   2.81,   46.12,    1.21,  249.87,    1.13],
       [   3.01,   46.05,    0.87,  289.71,    1.48],
       [   3.59,   46.31,    1.19,  287.77,    2.19],
       [   3.98,   41.74,    0.91,  207.68,    5.81],
       [   4.44,   43.56,    1.2 ,  568.56,    3.61],
       [   4.71,   47.2 ,    0.66,  242.69,    5.08],
       [   4.98,   46.64,    1.06,  276.65,    3.08]])

Reverse sort

In [14]:
# reverse sort
data[x[::-1], :][:10]

array([[  21.1 ,   27.01,    1.91, 1257.28,    8.21],
       [  18.56,   45.25,    0.56,  138.33,    5.14],
       [  16.85,   24.42,    3.93, 2496.53,    3.99],
       [  15.48,   32.54,    2.47,  601.05,    8.12],
       [  14.65,   24.71,    3.25, 1740.7 ,    7.66],
       [  14.28,   24.52,    3.48, 1390.  ,    3.54],
       [  14.13,   23.49,    3.73, 2630.96,    2.7 ],
       [  13.3 ,   31.92,    1.52,  250.96,    2.  ],
       [  13.17,   23.8 ,    4.43, 2108.47,    3.82],
       [  12.88,   42.19,    0.83,  728.47,    4.56]])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Lexsort</h2>
</div>

IF you want to sort based on more than one column, use `lexsort`.

Let's first round the data, so some values repeat.

In [15]:
data = data.round()
data[:10]

array([[  11.,   29.,    3., 2330.,    3.],
       [  12.,   23.,    4., 1508.,    4.],
       [  13.,   24.,    4., 2108.,    4.],
       [   6.,   42.,    2.,  189.,    0.],
       [  13.,   42.,    1.,  728.,    5.],
       [   9.,   32.,    3., 2983.,    2.],
       [   1.,   40.,    1.,  663.,    3.],
       [  12.,   45.,    1.,  290.,    7.],
       [   5.,   47.,    1.,  277.,    3.],
       [  11.,   48.,    1.,  471.,    3.]])

__Sort by 0th column first then by 1st column__

In [16]:
x = np.lexsort((data[:, 1].tolist(), data[:, 0].tolist())) 
x

array([18,  6, 31, 16, 41, 23, 30, 11, 40,  8, 49,  3, 38, 29, 42, 43, 46,
       17, 47,  5, 19, 48, 44, 24, 26, 15, 12,  0, 20, 35, 28,  9,  1, 37,
       34,  7, 14,  2, 13, 36,  4, 32, 33, 39, 21, 27, 25, 10, 45, 22],
      dtype=int64)

In [17]:
data[x, :][:15,:]

array([[   1.,   34.,    3., 1900.,    1.],
       [   1.,   40.,    1.,  663.,    3.],
       [   2.,   41.,    1.,  221.,    1.],
       [   3.,   46.,    1.,  290.,    1.],
       [   3.,   46.,    1.,  250.,    1.],
       [   4.,   42.,    1.,  208.,    6.],
       [   4.,   44.,    1.,  569.,    4.],
       [   4.,   46.,    1.,  288.,    2.],
       [   5.,   43.,    1.,  390.,    3.],
       [   5.,   47.,    1.,  277.,    3.],
       [   5.,   47.,    1.,  243.,    5.],
       [   6.,   42.,    2.,  189.,    0.],
       [   7.,   21.,    5., 3299.,    3.],
       [   7.,   45.,    1.,  326.,    2.],
       [   8.,   23.,    4., 1814.,    2.]])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge</h2>
</div>

Q. Sort 2nd column in ascending order and 4th column in descending order.

```python
import numpy as np
np.set_printoptions(suppress=True)  

data = np.genfromtxt("Datasets/Lifecyclesavings.csv", delimiter=",", skip_header=1)
data = data.round()
data[:10]
```

__Code URL:__ https://git.io/Jn8Ru

__Solution__

In [18]:
import numpy as np
np.set_printoptions(suppress=True)  

data = np.genfromtxt("Datasets/Lifecyclesavings.csv", delimiter=",", skip_header=1)
data = data.round()
data[:10]

array([[  11.,   29.,    3., 2330.,    3.],
       [  12.,   23.,    4., 1508.,    4.],
       [  13.,   24.,    4., 2108.,    4.],
       [   6.,   42.,    2.,  189.,    0.],
       [  13.,   42.,    1.,  728.,    5.],
       [   9.,   32.,    3., 2983.,    2.],
       [   1.,   40.,    1.,  663.,    3.],
       [  12.,   45.,    1.,  290.,    7.],
       [   5.,   47.,    1.,  277.,    3.],
       [  11.,   48.,    1.,  471.,    3.]])

In [19]:
# Sort 2nd ascending, 4th in descending.
x = np.lexsort([-data[:, 4], data[:, 2]])
data[x, :]

array([[  12.,   45.,    1.,  290.,    7.],
       [   4.,   42.,    1.,  208.,    6.],
       [  13.,   42.,    1.,  728.,    5.],
       [  19.,   45.,    1.,  138.,    5.],
       [   5.,   47.,    1.,  243.,    5.],
       [   4.,   44.,    1.,  569.,    4.],
       [   1.,   40.,    1.,  663.,    3.],
       [   5.,   47.,    1.,  277.,    3.],
       [  11.,   48.,    1.,  471.,    3.],
       [   8.,   47.,    1.,  232.,    3.],
       [   5.,   43.,    1.,  390.,    3.],
       [   4.,   46.,    1.,  288.,    2.],
       [   9.,   41.,    1.,   89.,    2.],
       [   7.,   45.,    1.,  326.,    2.],
       [  13.,   46.,    1.,  152.,    2.],
       [   3.,   46.,    1.,  290.,    1.],
       [   2.,   41.,    1.,  221.,    1.],
       [  13.,   44.,    1.,  400.,    1.],
       [   3.,   46.,    1.,  250.,    1.],
       [   9.,   46.,    1.,  813.,    1.],
       [   9.,   44.,    2.,  124.,   17.],
       [   8.,   41.,    2.,  380.,   10.],
       [  21.,   27.,    2., 125