<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Searchsorted and Bisect</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

When trying to insert a numbr into a sorted array, `Searchsorted` finds the position that will keep the array in sorted order.

In [1]:
import numpy as np
np.set_printoptions(threshold=2000)

In [2]:
np.random.seed(100)
a = np.random.randint(1, 100, size=1000)
a.sort()

In [3]:
a

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11,
       11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13,
       13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
       24, 24, 24, 24, 24

In [4]:
num = 6
pos = np.searchsorted(a, num)
pos

52

 If `side=right`, return the last such index.

In [5]:
np.searchsorted(a, num, side="right")

56

Insert in element by reconstructing the array.

In [6]:
# insert in element by reconstructing the array.
a1 = np.r_[a[:pos], num, a[pos:]]
a1[:100]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11])

In [7]:
np.searchsorted(a, [7, 65, 50, 90])

array([ 56, 637, 476, 894], dtype=int64)

In [8]:
%%timeit
np.searchsorted(a, [7, 65, 50, 90])

5.12 µs ± 319 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Bisect Module</h2>
</div>

The Bisect module provides a similar functionality as what `np.searchsorted` achieves. That is, it helps keeping a list in the sorted order after inserting a number without having to re-sort it.

In [9]:
import bisect

In [10]:
np.random.seed(100)
a = np.random.randint(1, 100, size=1000)
a.sort()

In [11]:
a[:100]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11])

In [12]:
num = 6
bisect.bisect(a, num)

56

In [13]:
bisect.bisect_left(a, num)

52

`bisect.insort_left` will insert the number at the earliest position to keep the list sorted. Likewise `bisect.insort_right` will insert at the latest position.

In [14]:
a = a.tolist()
bisect.insort_left(a, num)

In [15]:
print(a[:100])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11]


<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge</h2>
</div>

A school grades student scores based on their marks using the following breakpoints:

- `>90`  --> A
- `>80`  --> B
- `>50`  --> C
- `>30`  --> D
- `<=30` --> E

Use `np.searchsorted` to obtain the grades for the following scores: 20, 35, 41, 55, 81, 99.

Desired Output:
```
#> `['E', 'D', 'D', 'C', 'B', 'A']`
```

__Solution__

In [16]:
def get_grade(score, breaks=[30, 50, 80, 90], grades='EDCBA'):
    i = np.searchsorted(breaks, score)
    return grades[i]

[get_grade(score) for score in [20, 35, 41, 55, 81, 99]]

['E', 'D', 'D', 'C', 'B', 'A']