<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Vectorization</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

With the help of __vectorize()__ you can make a function that is meant to work on individual numbers, to work on arrays.

The function `prime_or_not` accepts a number and check if it is a prime number. When you apply this function on a scalar (individual numbers) it works perfectly, but fails when applied on an array or a list.

Numpy's vectorize funtion can make it work on list / array. 

In [1]:
import numpy as np

In [2]:
def prime_or_not(num):
    if num > 1:
        for i in range(2, num):
            if (num % i) == 0:
                return False
        else:
            return True
            
# On a scalar
print('x = 10 returns ', prime_or_not(10))
print('x = 11 returns ', prime_or_not(11))

x = 10 returns  False
x = 11 returns  True


__Calling it on an array or list does not work__

In [3]:
# DOES NOT WORK
prime_or_not([10, 11, 12])

TypeError: '>' not supported between instances of 'list' and 'int'

__Make foo() work on arrays__

Specify the type of the output to make in `otypes`

In [5]:
prime_or_not_v = np.vectorize(prime_or_not)

In [6]:
print('x = 10 returns ', prime_or_not_v(10))
print('x = 11 returns ', prime_or_not_v(11))

x = 10 returns  False
x = 11 returns  True


In [7]:
prime_or_not_v([10, 11, 12])

array([False,  True, False])

Explicit the output type.

In [8]:
prime_or_not_o = np.vectorize(prime_or_not, otypes=[bool])

Run on scalars

In [9]:
print('x = 10 returns ', prime_or_not_o(10))
print('x = 11 returns ', prime_or_not_o(11))

x = 10 returns  False
x = 11 returns  True


Run on vectors

In [10]:
prime_or_not_o([10, 11, 12])

array([False,  True, False])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge</h2>
</div>

Vectorize the `calc_profit` function to make it work for all the rows of the dataset.

```python
# Calc Profit
def calc_profit(open, high, low, close):
    buy = open * 0.999
    # daily range
    if low < buy < high:
        return (close - buy)/buy
    else:
        return 0
    
# Read Data
arr = np.genfromtxt("Datasets/apple_stock_price.csv", delimiter=",", skip_header=1)
arr

# array([[127.489998, 128.880005, 126.919998, 127.830002],
#        [127.629997, 128.779999, 127.449997, 128.720001],
#        [128.479996, 129.029999, 128.330002, 128.449997],
#        ...,
#        [133.470001, 135.089996, 133.25    , 135.020004],
#        [135.520004, 136.270004, 134.619995, 135.509995],
#        [135.669998, 135.899994, 134.839996, 135.350006]])
```

__Code URL:__ https://git.io/JnEvj

In [11]:
def calc_profit(open, high, low, close):
    buy = open * 0.999
    # daily range
    if low < buy < high:
        return (close - buy)/buy
    else:
        return 0

In [12]:
# Read data
arr = np.genfromtxt("Datasets/apple_stock_price.csv", delimiter=",", skip_header=1)
arr

array([[127.489998, 128.880005, 126.919998, 127.830002],
       [127.629997, 128.779999, 127.449997, 128.720001],
       [128.479996, 129.029999, 128.330002, 128.449997],
       ...,
       [133.470001, 135.089996, 133.25    , 135.020004],
       [135.520004, 136.270004, 134.619995, 135.509995],
       [135.669998, 135.899994, 134.839996, 135.350006]])

In [13]:
calc_profit(127.489998, 128.880005, 126.919998, 127.830002)

0.003670577828073656

#### Solution: Vectorize

In [14]:
calc_profit_vec = np.vectorize(calc_profit, otypes=[float])

In [15]:
output = calc_profit_vec(arr[:, 0], arr[:, 1], arr[:, 2], arr[:, 3])
output[:10]

array([ 0.00367058,  0.00954989,  0.00076728,  0.00784975,  0.02394346,
       -0.00479691, -0.02007515,  0.01366997, -0.01085696, -0.00023818])