<a href="https://colab.research.google.com/github/patelsaumya/numpy/blob/master/19_Apply%20a%20Function%20Along.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Apply Along Functions</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

Numpy provide the `apply_along_axis` functions to apply a particular function on all items along a specific axis, typically, to apply a function on all rows or all columns of a 2-d array.

In [ ]:
import numpy as np

In [ ]:
np.random.seed(100)
arr = np.random.randint(1,100, size=(50, 4))
arr

array([[ 9, 25, 68, 88],
       [80, 49, 11, 95],
       [53, 99, 54, 67],
       [99, 15, 35, 25],
       [16, 61, 59, 17],
       [10, 94, 87,  3],
       [28,  5, 32,  2],
       [14, 84,  5, 92],
       [60, 68,  8, 50],
       [48, 66, 62, 15],
       [56, 72, 81,  3],
       [95, 20, 99, 64],
       [54, 28, 57, 31],
       [49, 48, 40, 39],
       [45, 19, 65, 57],
       [35, 54, 75, 18],
       [73, 14, 31, 18],
       [54, 69, 51, 92],
       [92, 84, 54, 79],
       [ 1, 14, 58, 77],
       [ 4, 71,  4, 85],
       [80, 11, 88, 61],
       [ 4, 49, 53, 44],
       [37,  6, 72, 39],
       [87, 95, 99, 43],
       [85, 96, 77, 34],
       [59, 43, 23,  1],
       [56, 99, 20, 54],
       [69, 63, 51, 69],
       [36, 24, 10, 49],
       [22, 26, 55,  7],
       [38, 59, 40, 95],
       [52, 31, 67, 25],
       [56, 18, 46, 90],
       [46, 36, 17, 13],
       [87, 83, 68, 93],
       [96, 21, 11,  9],
       [90, 73, 31, 13],
       [19, 94, 93, 45],
       [58,  1, 74, 55],


In [ ]:
# Define func1d
def max_by_min(x):
    return np.max(x) / np.min(x)

# Apply along the rows
print('Row wise: \n', np.apply_along_axis(max_by_min, 1, arr=arr), '\n')

Row wise: 
 [ 9.77777778  8.63636364  1.86792453  6.6         3.8125     31.33333333
 16.         18.4         8.5         4.4        27.          4.95
  2.03571429  1.25641026  3.42105263  4.16666667  5.21428571  1.80392157
  1.7037037  77.         21.25        8.         13.25       12.
  2.30232558  2.82352941 59.          4.95        1.35294118  4.9
  7.85714286  2.5         2.68        5.          3.53846154  1.36764706
 10.66666667  6.92307692  4.94736842 74.         15.5         2.6
  1.72727273 42.5         4.47619048  2.86206897 31.66666667 30.33333333
  1.7962963   2.34482759] 



If you change the axis to 0, it will be applied column wise.

In [ ]:
# Apply along the columns
print('Column wise: \n', np.apply_along_axis(max_by_min, 0, arr=arr))

Column wise: 
 [99. 99. 33. 95.]


<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge</h2>
</div>

For the following dataset, compute and print the mean, median, min, max, std, 25%ile, 75%ile for every numeric column.

In [ ]:
import numpy as np
arr = np.genfromtxt("Datasets/iris.csv", delimiter=",", skip_header=1)
arr[:10, :]

array([[4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4]])

In [ ]:
# Solution:
def summary(x):
    return(np.nanmean(x), 
           np.nanmedian(x),
           np.nanmin(x),
           np.nanmax(x),
           np.nanstd(x),
           np.nanquantile(x,.25),
           np.nanquantile(x,.75))


In [ ]:
np.apply_along_axis(func1d=summary, axis=0, arr=arr)

array([[5.81238095, 3.07619048, 3.72666667, 1.18380952],
       [5.7       , 3.        , 4.2       , 1.3       ],
       [4.4       , 2.2       , 1.        , 0.1       ],
       [7.9       , 4.4       , 6.9       , 2.5       ],
       [0.78056088, 0.45366734, 1.74073146, 0.74259825],
       [5.2       , 2.8       , 1.6       , 0.3       ],
       [6.3       , 3.4       , 5.1       , 1.8       ]])