<a href="https://colab.research.google.com/github/patelsaumya/numpy/blob/master/20_More%20Useful%20Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>More Useful Functions</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

- __Digitize :__ Bin a numeric variable into predefined categories.
- __Clip:__ Clip a numeric variable to a defined min and max values.
- __Histogram:__ Produce the bins and the frequencies for a numeric variable. That is, the elements of a histogram.

In [ ]:
import numpy as np

arr = np.genfromtxt("Datasets/iris.csv", delimiter=",", skip_header=1)

dt = np.dtype({'names': ["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"],
               'formats': [np.float, np.float, np.float, np.float]})

arr.dtype = dt

arr[:10]

array([[(4.7, 3.2, 1.3, 0.2)],
       [(5. , 3.6, 1.4, 0.2)],
       [(5.4, 3.9, 1.7, 0.4)],
       [(4.6, 3.4, 1.4, 0.3)],
       [(4.9, 3.1, 1.5, 0.1)],
       [(5.4, 3.7, 1.5, 0.2)],
       [(4.8, 3.4, 1.6, 0.2)],
       [(4.8, 3. , 1.4, 0.1)],
       [(5.8, 4. , 1.2, 0.2)],
       [(5.7, 4.4, 1.5, 0.4)]],
      dtype=[('Sepal.Length', '<f8'), ('Sepal.Width', '<f8'), ('Petal.Length', '<f8'), ('Petal.Width', '<f8')])

In [ ]:
sepallength = arr['Sepal.Length'].reshape(-1, )
sepallength

array([4.7, 5. , 5.4, 4.6, 4.9, 5.4, 4.8, 4.8, 5.8, 5.7, 5.4, 5.1, 5.7,
       5.4, 5.1, 4.6, 5.1, 4.8, 5. , 5.2, 5.2, 4.7, 5.4, 5.2, 5.5, 4.9,
       5. , 4.9, 5. , 4.4, 5.1, 4.8, 4.6, 5.3, 5. , 5.5, 6.5, 5.7, 6.3,
       4.9, 6.6, 5.2, 5.9, 5.6, 6.7, 5.6, 6.2, 5.6, 6.3, 6.4, 5.7, 5.5,
       5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 6.1, 5.8, 5. , 5.6,
       5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3, 4.9, 7.3, 6.7, 7.2,
       6.5, 6.8, 6.5, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 6.2, 6.1, 6.4,
       7.4, 7.9, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 5.8, 6.7, 6.7, 6.5, 6.2,
       5.9])

__np.digitize__

 Bin a numeric variable to predefined categories. Numeric  -->  Categorical

In [ ]:
np.digitize(sepallength, bins=[0,5,6,7,10])

array([1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1,
       2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 3, 2, 3, 1, 3, 2, 2, 2,
       3, 2, 3, 2, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, 3, 2, 2, 3, 2, 2, 2, 2,
       2, 3, 2, 2, 3, 2, 4, 3, 1, 4, 3, 4, 3, 3, 3, 4, 3, 3, 2, 4, 3, 3,
       3, 3, 3, 4, 4, 3, 3, 4, 3, 3, 3, 2, 3, 3, 3, 3, 2], dtype=int64)

__Clip__

In [ ]:
np.clip(sepallength, 5, 7)

array([5. , 5. , 5.4, 5. , 5. , 5.4, 5. , 5. , 5.8, 5.7, 5.4, 5.1, 5.7,
       5.4, 5.1, 5. , 5.1, 5. , 5. , 5.2, 5.2, 5. , 5.4, 5.2, 5.5, 5. ,
       5. , 5. , 5. , 5. , 5.1, 5. , 5. , 5.3, 5. , 5.5, 6.5, 5.7, 6.3,
       5. , 6.6, 5.2, 5.9, 5.6, 6.7, 5.6, 6.2, 5.6, 6.3, 6.4, 5.7, 5.5,
       5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 6.1, 5.8, 5. , 5.6,
       5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7. , 6.3, 5. , 7. , 6.7, 7. ,
       6.5, 6.8, 6.5, 7. , 6. , 6.9, 5.6, 7. , 6.3, 6.7, 6.2, 6.1, 6.4,
       7. , 7. , 6.3, 6.1, 7. , 6.3, 6.4, 6. , 5.8, 6.7, 6.7, 6.5, 6.2,
       5.9])

__Histogram__

In [ ]:
np.histogram(sepallength, bins=10)

(array([ 6, 20, 11, 23,  9, 15, 12,  2,  3,  4], dtype=int64),
 array([4.4 , 4.75, 5.1 , 5.45, 5.8 , 6.15, 6.5 , 6.85, 7.2 , 7.55, 7.9 ]))

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Mini Challenge</h2>
</div>

Cap the following array at 10%ile and 90%ile values. Example: values below 10%ile should be replaced by 10%ile value.

```python
import numpy as np
np.random.seed(100)
arr = np.random.normal(30, 10, 100).round(2)
arr
```

__Code URL:__ https://git.io/Jn2pa

In [ ]:
# Create data
import numpy as np
np.random.seed(100)
arr = np.random.normal(30, 10, 100).round(2)
arr

array([12.5 , 33.43, 41.53, 27.48, 39.81, 35.14, 32.21, 19.3 , 28.11,
       32.55, 25.42, 34.35, 24.16, 38.17, 36.73, 28.96, 24.69, 40.3 ,
       25.62, 18.82, 46.19, 45.42, 27.48, 21.58, 31.85, 39.37, 37.31,
       43.62, 26.74, 30.56, 32.22, 15.57, 22.44, 38.16, 37.5 , 25.44,
       41.9 , 13.09, 16.44, 17.68, 24.56, 23.32, 30.07, 23.87, 43.  ,
       12.67, 20.17, 33.58, 13.86, 44.71, 18.12, 24.5 , 20.6 , 21.72,
       31.09, 35.08, 21.38, 42.49, 29.2 , 21.1 , 21.18, 30.19, 32.38,
       30.14, 13.64, 19.56, 36.13, 37.36, 40.27, 15.68, 11.59, 33.66,
       26.68, 23.11, 50.35, 24.49, 37.5 , 16.93, 35.81, 18.95, 36.9 ,
       36.87, 14.33, 39.05, 37.79, 34.28, 31.09, 30.28, 24.21, 18.01,
       12.94, 33.69, 48.77, 26.23, 48.32, 30.03, 29.24, 30.04, 28.15,
        5.13])

In [ ]:
# Solution
mini = np.quantile(arr, .10)
maxi = np.quantile(arr, .90)
print(mini, maxi)
np.clip(arr, a_min=mini, a_max=maxi)

15.669 41.56700000000001


array([15.669, 33.43 , 41.53 , 27.48 , 39.81 , 35.14 , 32.21 , 19.3  ,
       28.11 , 32.55 , 25.42 , 34.35 , 24.16 , 38.17 , 36.73 , 28.96 ,
       24.69 , 40.3  , 25.62 , 18.82 , 41.567, 41.567, 27.48 , 21.58 ,
       31.85 , 39.37 , 37.31 , 41.567, 26.74 , 30.56 , 32.22 , 15.669,
       22.44 , 38.16 , 37.5  , 25.44 , 41.567, 15.669, 16.44 , 17.68 ,
       24.56 , 23.32 , 30.07 , 23.87 , 41.567, 15.669, 20.17 , 33.58 ,
       15.669, 41.567, 18.12 , 24.5  , 20.6  , 21.72 , 31.09 , 35.08 ,
       21.38 , 41.567, 29.2  , 21.1  , 21.18 , 30.19 , 32.38 , 30.14 ,
       15.669, 19.56 , 36.13 , 37.36 , 40.27 , 15.68 , 15.669, 33.66 ,
       26.68 , 23.11 , 41.567, 24.49 , 37.5  , 16.93 , 35.81 , 18.95 ,
       36.9  , 36.87 , 15.669, 39.05 , 37.79 , 34.28 , 31.09 , 30.28 ,
       24.21 , 18.01 , 15.669, 33.69 , 41.567, 26.23 , 41.567, 30.03 ,
       29.24 , 30.04 , 28.15 , 15.669])