<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Matrix Operations</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

In [1]:
import numpy as np

In [2]:
np.random.seed(109)
A = np.arange(9).reshape(3,3)
B = np.random.randint(0, 9, (3,3))

print("A: \n",A)
print("B: \n",B)

A: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
B: 
 [[6 5 5]
 [0 1 4]
 [3 0 2]]


__Dot Product__

Multiplies Row of first matrix with corresponding column of second matrix for every element.

In [3]:
# Dot Product
np.dot(A, B)

array([[ 6,  1,  8],
       [33, 19, 41],
       [60, 37, 74]])

In [4]:
# Another notation for Dot Product
A @ B

array([[ 6,  1,  8],
       [33, 19, 41],
       [60, 37, 74]])

__Element wise Multiplication - Hadamard Product__

In [5]:
A * B

array([[ 0,  5, 10],
       [ 0,  4, 20],
       [18,  0, 16]])

In [6]:
# alternate
np.multiply(A, B)

array([[ 0,  5, 10],
       [ 0,  4, 20],
       [18,  0, 16]])

__Inverse of a matrix__

Inverse of a matrix is one where the dot product of a matrix and its inverse gives a Identity matrix (1's along the diagonals).

In [7]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.03508772, -0.1754386 ,  0.26315789],
       [ 0.21052632, -0.05263158, -0.42105263],
       [-0.05263158,  0.26315789,  0.10526316]])

In [8]:
B_inv @ B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Trying to compute the inverse of A is not possible. Because, an inverse exists only if the determinant of a matrix is not zero.  When the determinant of a matrix is zero, its called a singular matrix.

In [29]:
# doesnt work
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [30]:
np.linalg.det(A)

-306.0

__Determinant of a matrix__

Let's see how to calculate the determinant for a 2x2 matrix.

In [31]:
A = np.array([[3, 4], 
              [5, 6]])

np.linalg.det(A)

-1.9999999999999971

In [32]:
# Determinant calc
(3*6) - (4*5)

-2

__Rank of a matrix__

It is the maximum number of linearly independent columns of the matrix. Linearly independent column is one which cannot be expressed as a linear combination of the other columns.

In [33]:
A

array([[3, 4],
       [5, 6]])

In [34]:
np.linalg.matrix_rank(A)

2

__Example 2__

In [15]:
A2 = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
print("Rank of A:", np.linalg.matrix_rank(A2))

Rank of A: 3


__Matrix Power__ 

A matrix may be raised to an 'n'th power.  

In [16]:
np.linalg.matrix_power(A, 3)

array([[267, 332],
       [415, 516]])

In [17]:
A @ A @ A

array([[267, 332],
       [415, 516]])

__Eigenvalues and EigenVectors__

The number `w` is an eigenvalue of `a` if there exists a vector `v` such that ``a @ v = w * v``.

In [18]:
# Eigen values
arr = np.diag((1, 2, 3))
arr = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
print("Array: \n", arr)
 
# calculating an eigen value
w, v = np.linalg.eig(arr)
 
print("\nEigen value is : \n", w)
print("\nEigen vector is : \n", v)

Array: 
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

Eigen value is : 
 [11.24862343  5.09285054 -5.34147398]

Eigen vector is : 
 [[ 0.24511338  0.75669314  0.02645665]
 [ 0.40622202 -0.03352363 -0.84078293]
 [ 0.88028581 -0.65291014  0.54072554]]


__Check__

In [19]:
w * v

array([[ 2.7571881 ,  3.85372509, -0.1413175 ],
       [ 4.56943852, -0.17073086,  4.49102015],
       [ 9.90200356, -3.32517376, -2.88827139]])

In [20]:
arr @ v

array([[ 2.7571881 ,  3.85372509, -0.1413175 ],
       [ 4.56943852, -0.17073086,  4.49102015],
       [ 9.90200356, -3.32517376, -2.88827139]])

__QR Decomposition__

QR decomposition (or factorization) is a decomposition of a matrix A into a product A = QR of an orthogonal matrix Q and an upper triangular matrix R.

In [21]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [22]:
q, r = np.linalg.qr(A)
print("Q :", q, "\n")
print("R :", r)

Q : [[-0.80178373 -0.06178021 -0.59441237]
 [-0.53452248 -0.37068124  0.75952691]
 [-0.26726124  0.92670309  0.26418327]] 

R : [[-7.48331477 -1.87082869 -5.34522484]
 [ 0.          8.09320703  4.57173527]
 [ 0.          0.          5.05250513]]


__Check__

Dot product of q nd R results in the orininal matrix.

In [23]:
q @ r   # reconstruct A

array([[ 6.,  1.,  1.],
       [ 4., -2.,  5.],
       [ 2.,  8.,  7.]])

__Singular Value Decomposition (SVD)__

Decomposes a given matrix into its 3 constituent matrices P, D and Q.

In [24]:
X = np.random.normal(size=[10,6])
X

array([[-0.17768802, -0.83874355, -0.15628712, -0.34176163,  0.81873029,
        -0.09261394],
       [ 0.50808094, -1.7542225 , -0.36481798, -0.03091855, -0.12614427,
         0.299181  ],
       [ 1.82207405,  1.41717686, -0.45731622,  0.86019957,  0.28468256,
         0.51062749],
       [ 1.57829456,  0.16130871,  0.71819658, -0.80599584, -0.59818081,
         1.32383635],
       [ 1.13726714, -0.48833019,  0.34806743, -0.97086135, -0.21213643,
         0.42335106],
       [ 0.10377004,  0.05097481, -0.67144065,  0.27170251,  0.00701349,
         0.32662299],
       [ 0.03618145, -1.19327841, -0.15810171,  0.01341776, -0.47234681,
        -0.20810645],
       [ 1.44154411, -1.67109527,  0.54455933,  1.26132175,  0.96283701,
        -0.27990168],
       [-0.23044776,  0.45213427, -0.35421077,  0.34015305,  0.63620222,
         0.75003234],
       [ 1.3507378 , -0.28858894,  0.08703628, -0.08413142, -0.99903647,
         0.10133759]])

In [25]:
P, D, Q = np.linalg.svd(X, full_matrices=False)

In [26]:
print(P.shape)
print(D.shape)
print(Q.shape)

(10, 6)
(6,)
(6, 6)


In [27]:
X_svd = P @ np.diag(D) @ Q
X_svd

array([[-0.17768802, -0.83874355, -0.15628712, -0.34176163,  0.81873029,
        -0.09261394],
       [ 0.50808094, -1.7542225 , -0.36481798, -0.03091855, -0.12614427,
         0.299181  ],
       [ 1.82207405,  1.41717686, -0.45731622,  0.86019957,  0.28468256,
         0.51062749],
       [ 1.57829456,  0.16130871,  0.71819658, -0.80599584, -0.59818081,
         1.32383635],
       [ 1.13726714, -0.48833019,  0.34806743, -0.97086135, -0.21213643,
         0.42335106],
       [ 0.10377004,  0.05097481, -0.67144065,  0.27170251,  0.00701349,
         0.32662299],
       [ 0.03618145, -1.19327841, -0.15810171,  0.01341776, -0.47234681,
        -0.20810645],
       [ 1.44154411, -1.67109527,  0.54455933,  1.26132175,  0.96283701,
        -0.27990168],
       [-0.23044776,  0.45213427, -0.35421077,  0.34015305,  0.63620222,
         0.75003234],
       [ 1.3507378 , -0.28858894,  0.08703628, -0.08413142, -0.99903647,
         0.10133759]])

In [28]:
print('Is X  and X_svd close?', np.isclose(X, X_svd).all())

Is X  and X_svd close? True
