<div style="color:#006666; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Solving Linear Equations</h1>
<hr>
<p style="color:#006666; text-align:right;font-size:10px">
Copyright by MachineLearningPlus. All Rights Reserved.
</p>

</div>

Linear equations can be easily solved with numpy using the `np.linalg.solve()` method. 

To do this, you need to define the LHS and RHS of the equarions as two different arrays and use them as arguments to `np.linalg.solve`.

Example: 
Company A offers to pay 450 Dollars per week and Company B pays 10 Dollars per hour. You work 40 hours per week. Which company offers a better rate of pay? 



<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Equation with Two Variables</h2>
</div>

In [1]:
import numpy as np
  
# Coefficients
A = np.array([[1, 2], [3, 4]])

# Constants
b = np.array([8, 10])

__Equations:__

1X + 2Y = 8

3X + 4Y = 10

__Solve__

In [2]:
x = np.linalg.solve(A, b)
print("Solution", x)

Solution [-6.  7.]


__Check__

In [3]:
np.dot(A , x)

array([ 8., 10.])

<div class="alert alert-info" style="background-color:#006666; color:white; padding:0px 10px; border-radius:5px;"><h2 style='margin:7px 5px; font-size:16px'>Three Variable Example</h2>
</div>

In [4]:
A = np.mat([[1, -2,  1],
            [0,  2, -8],
            [-4, 5,  9]])

print("A\n", A)

b = np.array([0, 8, 4])
print("b\n", b)

A
 [[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]
b
 [0 8 4]


__Equations:__

1X - 2Y + Z = 0

0X + 2Y - 8Z = 8

-4X + 5Y + 9Z = 4


__Solve__

In [5]:
x = np.linalg.solve(A, b)
print("Solution", x)

Solution [120.  68.  16.]


__Check Solutions__

In [6]:
np.dot(A , x)

matrix([[0., 8., 4.]])